tasks:
  - before: |
      chmod +x ./setup.sh
      sudo ./setup.sh
  - init: |
      sudo docker-compose pull
  - command: |
      sudo docker-compose up
ports:
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: open-browser
  - port: 14259
    onOpen: ignore

vscode:
  extensions:
    - redhat.vscode-yaml
    - ms-azuretools.vscode-docker
    - ms-vscode.live-server

github:
  prebuilds:
    pullRequests: false
    pullRequestsFromForks: false
    addComment: false
    addBadge: false
