site_name: DB Stack
site_url: https://zacharlie.github.io/spatial-dbstack/
site_author: I am not a cat
site_description: >-
  User docs for the spatial dbstack
repo_name: dbstack
repo_url: https://github.com/zacharlie/spatial-dbstack
edit_uri: "https://github.com/zacharlie/spatial-dbstack/blob/main/mkdocs/src/"

docs_dir: mkdocs/src
site_dir: docs

# Copyright
copyright: Copyfree Content

nav:
  - Home: index.md
  - Quickstart:
      - Deployment: start/deployment.md
      - Service Information: start/service-information.md
  - FAQ: faq/faq.md
  - Architecture:
      - Design: architecture/design.md
  - Library:
      - Snippets: library/snippets.md
      - Grafana Queries: library/grafana.md
  - Tutorials:
      - QGIS: tutorials/qgis/index.md

# Configuration
theme:
  name: material
  custom_dir: mkdocs/

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: gray
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: gray
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  icon:
    logo: material/database

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zacharlie/spatial-dbstack

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .
  - pymdownx.details
  - admonition

plugins:
  - search
