global:
  scrape_interval: 10s
  scrape_timeout: 2s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: grafana
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["grafana:3000"]
